export const CATEGORY_ACTION_TYPE = {
    // SET_CATEGORY_ARRAY : 'SET_CATEGORY_ARRAY',
    FETCH_CATEGORY_ARRAY_START : 'category/FETCH_CATEGORY_ARRAY_START',
    FETCH_CATEGORY_ARRAY_SUCCESS : 'category/FETCH_CATEGORY_ARRAY_SUCCESS',
    FETCH_CATEGORY_ARRAY_FAILED : 'category/FETCH_CATEGORY_ARRAY_FAILED',
}